### ISSUE TITLE
Upgrade to CDK v2?

### ISSUE THREAD

**Issue by ehalsey** [aws-samples/aws-cdk-deploy-pipeline-using-aws-codepipeline#3]
Hi - I was wondering if there is a timeline to upgrade this to use cdk v2 since [aws-cdk-project-template-for-devops](https://github.com/aws-samples/aws-cdk-project-template-for-devops) has been upgraded.

**Comment by kwonyulchoi** [comment]
Thank you for attention~

I already support CDK ver2 in branch "release_cdk_v2". `README.md` document is also describing that in `Prerequisite`.

So you can clone it through the following command:

```shell
git clone https://github.com/aws-samples/aws-cdk-deploy-pipeline-using-aws-codepipeline.git -b release_cdk_v2
```
