### ISSUE TITLE
change deployed bucket policy for enterprise security compliance

### ISSUE THREAD

**Issue by gagipro** [aws-samples/aws-cdk-deploy-pipeline-using-aws-codepipeline#6]
Hello,

I wonder what is the best way to extend classes for deployed buckets.

How can we add bucket policies to be compliant with enterprise security at deployment and not outside of the deployed stack?

thanks.

**Comment by kwonyulchoi** [comment]
Could you explain more detail?

**Comment by gagipro** [comment]
> Could you explain more detail?

With L2 construct, you have to predeclare the bucket used by codepipeline to be able to apply changes on it.
